PoliquinInterviewProject/Models/ModelState.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PoliquinInterviewProject.Models
{
    /// <summary>
    /// Model for holding data related to a state entity.
    /// </summary>
    public class ModelState
    {
        public string Name { get; set; }
        public string LargestCity { get; set; }
        public long Area { get; set; }
    }
}

PoliquinInterviewProject/Controllers/InterviewController.cs
using PoliquinInterviewProject.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace PoliquinInterviewProject.Controllers
{
    public class InterviewController : Controller
    {
        private const string DEFAULT_MESSAGE = @"You found a bug! Can you fix it? Can you explain what caused the bug and how to avoid it in the future?";

        /// <summary>
        /// Returns the view for the landing page.
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Returns a view for selecting a state.
        /// </summary>
        /// <returns></returns>
        public async Task<ActionResult> SelectState()
        {
            var adapter = Factory.GetDefault();
            var list = await adapter.GetStatesAsync();
            TempData["list"] = list;
            return View(list);
        }

        /// <summary>
        /// Returns a view displaying statistic for a selected state.
        /// </summary>
        /// <param name="stateName">The name of the state for which to display the statistics.</param>
        /// <returns></returns>
        public ActionResult DisplayStateStatistics(string stateName)
        {
            ViewBag.Message = DEFAULT_MESSAGE;

            var list = (IEnumerable<Models.ModelState>) TempData["list"];
            if (list !=null)
            {
                var state = list.Where(i => string.Compare(i.Name, stateName) == 0).FirstOrDefault();
                if (state != null)
                {                    
                    ViewBag.Message = string.Format("The largest city in {0} is {1}. The state has an area of {2:N0} sq/km.", state.Name, state.LargestCity, state.Area);
                }
            }

            return View();
        }
    }
}

PoliquinInterviewProject/Views/Interview/DisplayStateStatistics.cshtml
@{
    ViewBag.Title = "DisplayStateStatistics";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>State Statistics</h2>

@ViewBag.Message

PoliquinInterviewProject/Views/Interview/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Welcome to The Poliquin Group!</h2>

<p>
    This exercise should not take you more than one hour to complete. The results of this project will be used in discussions during future interviews.
</p>
<p>
    <b>To complete this project:</b>
</p>
<ol>
    <li>Ensure all Unit Tests are passing. Two are currently failing. The code you write to get these tests passing will be used in the next exercise(s).</li>    
    <li>Modify the application so that the state with the most similar area is also displayed on the <b>State Statistics</b> page.
        <ul>
            <li>Additional text should say something like "The state most closely related in size is California with 423,968 sq/km."</li>
        </ul>
    </li>
    <li>Modify the application so the state (with the most similar area) displayed in #2 above is clickable. When clicked, the user should be redirected to the <b>State Statistics</b> page for that particular state.</li>
</ol>

<p>
    <b>What we're looking for:</b>
</p>
<ul>
    <li>Elegance - is your solution elegant?</li>
    <li>Readability - is your code easily readable... by a junior developer for instance?</li>
    <li>Documentation - did you clearly document your code so that your intentions are understood by future developers?</li>
    <li>Adaptability - did you write code/documentation that matches the style and architecture of the project?</li>
</ul>

PoliquinInterviewProject/Views/Interview/SelectState.cshtml
@model IEnumerable<PoliquinInterviewProject.Models.ModelState>

@{
    ViewBag.Title = "Select a State";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Question 1</h2>

<ul>
    @foreach (var state in Model)
    {
        <li>@Html.ActionLink(state.Name, "DisplayStateStatistics", new { stateName = state.Name })</li>
    }
</ul>

PoliquinInterviewProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title - Poliquin Interview</title>
</head>
<body>
    @Html.ActionLink("Index", "Index", "Interview") |
    @Html.ActionLink("Select a State", "SelectState", "Interview")

    <div>
        @RenderBody()
    </div>
</body>
</html>